---
title: 'Lab 1: FPGA and MCU Setup and Testing'
author: 'Christian Wu'
date: '09/02/25'
format:
    html:
        code-links:
         - text: "Lab 1 Github Repo"
           href: https://github.com/chrwu17/e155-lab1
           icon: github
---

## Introduction
The goal of this lab was to set up our E155 Board, soldering on all the necessary components, testing that the board functions with our FPGA and MCU, and writing code to display all hexadecimal digits on a 7-segment display and program onboard SMD LEDs

## Board Preparation
To prepare the development board for use, all the necessary components needed to be soldered on. This includes the 5V and 3.3 V Regulators, the necessary SMT Resistors, Capacitors, and Diodes, and all the necesary THT buttons, switches, and female connector pins. I followed the [Interactive Development Board BOM](https://hmc-e155.github.io/assets/doc/E155_v4_Dev_Board_BOM.html) to keep track of all the components that I soldered. 

The parts that gave me the most trouble while soldering were the two voltage regulators, as I could not get them to adhere to the solder and stay on the board. I was not able to melt the solder while making contact with the regulator, but after a while of trial and error and guidance from Xavier, I was able to get it to work. Other than that, the rest of the components were straight forward to solder, and the step by step suggestions on the course website aided the process. 

Below, is a picture of my fully assembled Development Board

INSERT IMAGE


## Board Testing
To test whether the board was soldered and assembled correctly, and that the FPGA and MCU are working correctly, I first followed the [Lattice Radiant iCE40 UltraPlus Project Setup Tutorial](https://hmc-e155.github.io/tutorials/tutorial-posts/lattice-radiant-ice40-ultraplus-project-setup). All of the setup on Radiant went smoothly, however, I had difficulty in programming onto my FPGA. On my personal laptop, the Programmer software would crash everytime I clicked the 'detect cable button', and on the lab computers, I would get an FTDI error when uploading code to the FPGA. I was unable to fix this issue for around 3 days, until a new programming method was uploaded (Thank you Kavi!). Thus, I followed the [openFPGALoader Programmer Tutorial](https://hmc-e155.github.io/tutorials/tutorial-posts/openfpgaloader-programmer/index.html) and was able to successfully program my FPGA. This allowed me to finish the tutorial and successfully see the onboard LED D6 at P42 blinking. 

I continued to do further testing on the FPGA as well as the MCU, I downloaded test code from the [course Lab 1 Github Repo](https://github.com/HMC-E155/hmc-e155/tree/main/lab/lab01) and programmed onto my board. After running the code on both my FPGA and MCU, I saw that when I had SW7 switched on, LED D3 (PA9/P25), LED D2 (PA10/P23), and LED D7 (P38) were all blinking. 

This means that I have successfully tested by development board, FPGA, and MCU, so I know that all my components are working as expected. 

## FPGA Design

### Objective

### Design

#### Block Diagram

#### LED Design

#### Seven Segment Display Design

### Testbench Simulation and Testing

### Hardware Design

## AI Prototype

## Hours Spent
I spent 23 hours on this lab.